apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: engahmedsaid125/auth
          env:
            - name: clientId
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: jwt_secret
              value: ahmed792002
            - name: db_url
              value: "mongodb://auth-mongo-srv:27017/auth"
            - name: clusterId
              value: tours
            - name: url
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-nodeport
spec:
  type: NodePort
  selector:
    app: auth
  ports:
  - port: 5000
    targetPort: 5000