apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: engahmedsaid125/review
          env:
            - name: clientId
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: jwt_secret
              value: ahmed792002
            - name: db_url
              value: "mongodb://review-mongo-srv:27017/review"
            - name: clusterId
              value: tours
            - name: url
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: review-srv
spec:
  selector:
    app: review
  ports:
  - port: 5002
    targetPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: review-nodeport
spec:
  type: NodePort
  selector:
    app: review
  ports:
  - port: 5002
    targetPort: 5002