apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tour
  template:
    metadata:
      labels:
        app: tour
    spec:
      containers:
        - name: tour
          image: engahmedsaid125/tour
          env:
            - name: clientId
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: jwt_secret
              value: ahmed792002
            - name: db_url
              value: "mongodb://tour-mongo-srv:27017/auth"
            - name: clusterId
              value: tours
            - name: url
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: tour-srv
spec:
  selector:
    app: tour
  ports:
  - port: 5001
    targetPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: tour-nodeport
spec:
  type: NodePort
  selector:
    app: tour
  ports:
  - port: 5001
    targetPort: 5001



